### ISSUE TITLE
Error when building on Kali

### ISSUE THREAD

**Issue by righettod** [d4rckh/gorilla#1]
Hi,

First, thank you very much for this amazing tool 👍 

I have the following error when I compile it on a Kali Linux:

![image](https://user-images.githubusercontent.com/1573775/184285098-c057fc5c-643c-4f59-b7a0-63e6c65e9bc8.png)

However, if I comment the following line of the `Cargo.toml` file then it's OK:

```
strip = "symbols"
```

I used the following version of Cargo:

```
$ cargo --version
cargo 1.56.0
```

Did I miss something in the build process?

Thank you very much in advance for your feedback 😃

**Comment by d4rckh** [comment]
try changing it to and try again 

strip = true

**Comment by d4rckh** [comment]
I also noticed your cargo version is pretty old. I'm using 1.62.1

**Comment by righettod** [comment]
OK thank you I will update my rust instance 😃
